/**
 * State Definitions — بارا السالفة
 * Defines the complete Game State Machine for this game.
 */

export const STATES = {
  IDLE: 'IDLE',
  PLAYER_SETUP: 'PLAYER_SETUP',
  ROLE_DISTRIBUTION: 'ROLE_DISTRIBUTION',
  SECRET_REVEAL: 'SECRET_REVEAL',
  QUESTION_PHASE: 'QUESTION_PHASE',
  VOTING: 'VOTING',
  VOTE_RESULT: 'VOTE_RESULT',
  TIEBREAKER: 'TIEBREAKER',
  IMPOSTER_GUESS: 'IMPOSTER_GUESS',
  ROUND_RESULT: 'ROUND_RESULT',
  SCORE_UPDATE: 'SCORE_UPDATE',
  GAME_END: 'GAME_END',
};

export const EVENTS = {
  START_GAME: 'START_GAME',
  CONFIRM_PLAYERS: 'CONFIRM_PLAYERS',
  ROLES_ASSIGNED: 'ROLES_ASSIGNED',
  ALL_REVEALED: 'ALL_REVEALED',
  START_VOTING: 'START_VOTING',
  ALL_VOTED: 'ALL_VOTED',
  TIE_DETECTED: 'TIE_DETECTED',
  IMPOSTER_CAUGHT: 'IMPOSTER_CAUGHT',
  IMPOSTER_SAFE: 'IMPOSTER_SAFE',
  REVOTE_COMPLETE: 'REVOTE_COMPLETE',
  GUESS_SUBMITTED: 'GUESS_SUBMITTED',
  NEXT_ROUND: 'NEXT_ROUND',
  END_GAME: 'END_GAME',
  RESTART_GAME: 'RESTART_GAME',
};

/**
 * Transition table: { fromState: { event: toState } }
 */
export const TRANSITIONS = {
  [STATES.IDLE]: {
    [EVENTS.START_GAME]: STATES.PLAYER_SETUP,
  },
  [STATES.PLAYER_SETUP]: {
    [EVENTS.CONFIRM_PLAYERS]: STATES.ROLE_DISTRIBUTION,
  },
  [STATES.ROLE_DISTRIBUTION]: {
    [EVENTS.ROLES_ASSIGNED]: STATES.SECRET_REVEAL,
  },
  [STATES.SECRET_REVEAL]: {
    [EVENTS.ALL_REVEALED]: STATES.QUESTION_PHASE,
  },
  [STATES.QUESTION_PHASE]: {
    [EVENTS.START_VOTING]: STATES.VOTING,
  },
  [STATES.VOTING]: {
    [EVENTS.ALL_VOTED]: STATES.VOTE_RESULT,
  },
  [STATES.VOTE_RESULT]: {
    [EVENTS.TIE_DETECTED]: STATES.TIEBREAKER,
    [EVENTS.IMPOSTER_CAUGHT]: STATES.IMPOSTER_GUESS,
    [EVENTS.IMPOSTER_SAFE]: STATES.ROUND_RESULT,
  },
  [STATES.TIEBREAKER]: {
    [EVENTS.ALL_VOTED]: STATES.VOTE_RESULT,
  },
  [STATES.IMPOSTER_GUESS]: {
    [EVENTS.GUESS_SUBMITTED]: STATES.ROUND_RESULT,
  },
  [STATES.ROUND_RESULT]: {
    [EVENTS.NEXT_ROUND]: STATES.ROLE_DISTRIBUTION,
    [EVENTS.END_GAME]: STATES.GAME_END,
  },
  [STATES.GAME_END]: {
    [EVENTS.RESTART_GAME]: STATES.PLAYER_SETUP,
    [EVENTS.START_GAME]: STATES.PLAYER_SETUP,
  },
};
